blueprint:
  name: Tado temperature offset
  description: Ensure the Tado smart valve has the temp of a separate sensor
  domain: automation
  input:
    source_temp_sensor:
      name: Source Temperature sensor
      description: This sensor will be used as the source.
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - temperature
          multiple: false
    target_tado:
      name: Tado
      description: The Tado to set the offset on.
      selector:
        entity:
          domain:
            - climate
          multiple: false
  source_url: https://gist.github.com/sanderma/1e9163c690e23bc8d32a8c9e9d89a910
variables:
  target_tado: !input target_tado
  source_temp_sensor: !input source_temp_sensor
  tado_temp: '{{ state_attr(target_tado, "current_temperature") | float }}'
  current_offset: '{{ state_attr(target_tado, "offset_celsius") | float(0) }}'
  actual_temp: '{{ states(source_temp_sensor) | float }}'
  offset: '{{ (actual_temp - tado_temp) | round }}'
  calculated_offset: '{{ (actual_temp - tado_temp + current_offset) | round(2) }}'
  dynamic_timeout: >
    {% set change_rate = states(source_temp_sensor).state | float - tado_temp %}
    {% if change_rate > 0.5 %}
      300 # Short timeout for rapid temperature changes
    {% elif change_rate > 0.1 %}
      600 # Moderate timeout for moderate temperature changes
    {% else %}
      900 # Longer timeout for slow temperature changes
    {% endif %}
trigger:
  - platform: state
    entity_id: !input target_tado
    attribute: current_temperature
  - platform: state
    entity_id: !input source_temp_sensor
condition:
  - condition: template
    value_template: '{{ offset != 0 }}'
  - condition: template
    value_template: '{{ actual_temp != 0 }}'
  - condition: template
    value_template: >
      {{ (as_timestamp(now()) - as_timestamp(state_attr('automation.tado_temperature_offset', 'last_triggered') | default(0))) > 900 }}
action:
  - wait_for_trigger:
      - platform: state
        entity_id: !input source_temp_sensor
        id: source_temp_state_change
      - platform: state
        entity_id: !input target_tado
        id: tado_temp_state_change
      - platform: state
        entity_id: !input source_temp_sensor
        id: source_temp_change
      - platform: state
        entity_id: !input target_tado
        id: tado_temp_change
    timeout: "{{ dynamic_timeout }}"
    continue_on_timeout: true
  - service: system_log.write
    data:
      message: '{{ target_tado }} has temp difference of {{ offset }}. Setting offset to {{ calculated_offset }}'
      level: info
      logger: blueprints.tado.offset
  - service: system_log.write
    data:
      message: 'target: {{ target_tado }}  source: {{ source_temp_sensor }} temp difference: {{ offset }} actual_temp: {{ actual_temp }} tado_temp: {{ tado_temp }} current_offset: {{ current_offset }} calculated_offset: {{ calculated_offset }}'
      level: debug
      logger: blueprints.tado.offset
  - service: tado.set_climate_temperature_offset
    data:
      offset: '{{ calculated_offset }}'
      entity_id: '{{ target_tado }}'
mode: single
